### ISSUE TITLE
Dex config

### ISSUE THREAD

**Issue by wdavidw** [adaltas/ece-webtech-2021-fall#19]
```yaml
# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: http://127.0.0.1:5556/dex

# The storage configuration determines where dex stores its state. Supported
# options include SQL flavors and Kubernetes third party resources.
#
# See the storage document at Documentation/storage.md for further information.
storage:
  type: sqlite3
  config:
    file: examples/dex.db

# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

# Configuration for telemetry
telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: webtech-frontend
  redirectURIs:
  - 'http://127.0.0.1:3000'
  name: 'WetTech Front End Chat Server'
  public: true

connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: xxxx98f1c26493dbxxxx
    clientSecret: xxxxxxxxx80e139441b637796b128d8xxxxxxxxx
    redirectURI: http://127.0.0.1:5556/dex/callback

# Let dex keep a list of passwords which can be used to login to dex.
enablePasswordDB: true

# A static list of passwords to login the end user. By identifying here, dex
# won't look in its underlying storage for passwords.
#
# If this option isn't chosen users may be added through the gRPC API.
staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

```
